// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3tT61HLDloGIYyFR7HCTv9AKxPrgehQY',
    appId: '1:682846702931:web:d9ca928b379847ba7525a6',
    messagingSenderId: '682846702931',
    projectId: 'poultry-pro-110ea',
    authDomain: 'poultry-pro-110ea.firebaseapp.com',
    storageBucket: 'poultry-pro-110ea.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLClT18JvPOGDEdvvW48L1ruOlsC_nYGY',
    appId: '1:682846702931:android:f632e4e9e43e822b7525a6',
    messagingSenderId: '682846702931',
    projectId: 'poultry-pro-110ea',
    storageBucket: 'poultry-pro-110ea.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCd5kMz3WltBQHUzXiPE1voI4gqCELxEMs',
    appId: '1:682846702931:ios:1e9dfa0075f9ecb87525a6',
    messagingSenderId: '682846702931',
    projectId: 'poultry-pro-110ea',
    storageBucket: 'poultry-pro-110ea.firebasestorage.app',
    iosBundleId: 'com.example.poultryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCd5kMz3WltBQHUzXiPE1voI4gqCELxEMs',
    appId: '1:682846702931:ios:1e9dfa0075f9ecb87525a6',
    messagingSenderId: '682846702931',
    projectId: 'poultry-pro-110ea',
    storageBucket: 'poultry-pro-110ea.firebasestorage.app',
    iosBundleId: 'com.example.poultryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3tT61HLDloGIYyFR7HCTv9AKxPrgehQY',
    appId: '1:682846702931:web:cdda1a0103f0d6dc7525a6',
    messagingSenderId: '682846702931',
    projectId: 'poultry-pro-110ea',
    authDomain: 'poultry-pro-110ea.firebaseapp.com',
    storageBucket: 'poultry-pro-110ea.firebasestorage.app',
  );

}