name: poultry_manager
description: Poultry farm management - simple, clear, business-oriented
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # Firebase
  firebase_core: ^4.6.0
  firebase_auth: ^6.3.0
  cloud_firestore: ^6.2.0

  # State management
  provider: ^6.1.5+1

  # Utils
  intl: ^0.20.2
  uuid: ^4.5.1

  # PDF
  pdf: ^3.10.7
  printing: ^5.12.0

  # Charts
  fl_chart: ^0.68.0

  # 🔥 OUVRIR LE LIEN DE PAIEMENT
  url_launcher: ^6.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true